server:
  port: 8081
  servlet:
    context-path: /gis

spatial:
  datasource:
    host: localhost
    port: 5432
    database: test
    user: xyj
    password: 1234
    schema: public
    type: postgis

spring:
  application:
    name: gis-server